// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "github.com/wwater/course-dao/app/medal/api/internal/handler/auth"
	medal "github.com/wwater/course-dao/app/medal/api/internal/handler/medal"
	"github.com/wwater/course-dao/app/medal/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/nonce",
				Handler: auth.GetNonceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail/:tokenId",
				Handler: medal.GetMedalDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list/:address",
				Handler: medal.GetMedalsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/medals"),
	)
}
