// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"github.com/wwater/course-dao/app/medal/api/internal/handler/medal"
	"net/http"

	auth "github.com/wwater/course-dao/app/medal/api/internal/handler/auth"
	course "github.com/wwater/course-dao/app/medal/api/internal/handler/course"
	"github.com/wwater/course-dao/app/medal/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/medals/:address",
				Handler: medal.GetMedalsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/medals/detail/:tokenId",
				Handler: medal.GetMedalDetailHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 钱包签名登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 获取登录随机数
				Method:  http.MethodPost,
				Path:    "/nonce",
				Handler: auth.GetNonceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckMedalMiddleware},
			[]rest.Route{
				{
					// 获取高级课程视频 (仅限 Course DAO 勋章持有者)
					Method:  http.MethodGet,
					Path:    "/premium",
					Handler: course.GetPremiumCourseHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/course"),
	)
}
