// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CourseReq struct {
}

type CourseResp struct {
	VideoUrl string `json:"video_url"`
	Title    string `json:"title"`
}

type ListProposalsReq struct {
	Page uint32 `form:"page,optional"`
	Size uint32 `form:"size,optional"`
}

type ListProposalsResp struct {
	List  []Proposal `json:"list"`
	Total int64      `json:"total"`
}

type Proposal struct {
	Id          string `json:"id"`
	Proposer    string `json:"proposer"`
	Description string `json:"description"`
	Amount      string `json:"amount"`
	Receiver    string `json:"receiver"`
	VotesFor    string `json:"votesFor"`
	Executed    bool   `json:"executed"`
	Deadline    int64  `json:"deadline"`
}

type ProposalDetailReq struct {
	Id string `path:"id"`
}
