// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.22.2
// source: medal.proto

package medal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Medal_GetMedalsByAddress_FullMethodName = "/medal.Medal/GetMedalsByAddress"
	Medal_GetMedalProof_FullMethodName      = "/medal.Medal/GetMedalProof"
	Medal_GetMedalByTokenId_FullMethodName  = "/medal.Medal/GetMedalByTokenId"
)

// MedalClient is the client API for Medal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MedalClient interface {
	// 根据地址获取勋章列表
	GetMedalsByAddress(ctx context.Context, in *GetMedalsReq, opts ...grpc.CallOption) (*GetMedalsResp, error)
	// 根据地址获取勋章证明
	GetMedalProof(ctx context.Context, in *GetMedalProofReq, opts ...grpc.CallOption) (*GetMedalProofResp, error)
	// 根据tokenId获取勋章详情
	GetMedalByTokenId(ctx context.Context, in *GetMedalByTokenIdReq, opts ...grpc.CallOption) (*MedalDetail, error)
}

type medalClient struct {
	cc grpc.ClientConnInterface
}

func NewMedalClient(cc grpc.ClientConnInterface) MedalClient {
	return &medalClient{cc}
}

func (c *medalClient) GetMedalsByAddress(ctx context.Context, in *GetMedalsReq, opts ...grpc.CallOption) (*GetMedalsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedalsResp)
	err := c.cc.Invoke(ctx, Medal_GetMedalsByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medalClient) GetMedalProof(ctx context.Context, in *GetMedalProofReq, opts ...grpc.CallOption) (*GetMedalProofResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedalProofResp)
	err := c.cc.Invoke(ctx, Medal_GetMedalProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medalClient) GetMedalByTokenId(ctx context.Context, in *GetMedalByTokenIdReq, opts ...grpc.CallOption) (*MedalDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedalDetail)
	err := c.cc.Invoke(ctx, Medal_GetMedalByTokenId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedalServer is the server API for Medal service.
// All implementations must embed UnimplementedMedalServer
// for forward compatibility.
type MedalServer interface {
	// 根据地址获取勋章列表
	GetMedalsByAddress(context.Context, *GetMedalsReq) (*GetMedalsResp, error)
	// 根据地址获取勋章证明
	GetMedalProof(context.Context, *GetMedalProofReq) (*GetMedalProofResp, error)
	// 根据tokenId获取勋章详情
	GetMedalByTokenId(context.Context, *GetMedalByTokenIdReq) (*MedalDetail, error)
	mustEmbedUnimplementedMedalServer()
}

// UnimplementedMedalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMedalServer struct{}

func (UnimplementedMedalServer) GetMedalsByAddress(context.Context, *GetMedalsReq) (*GetMedalsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMedalsByAddress not implemented")
}
func (UnimplementedMedalServer) GetMedalProof(context.Context, *GetMedalProofReq) (*GetMedalProofResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMedalProof not implemented")
}
func (UnimplementedMedalServer) GetMedalByTokenId(context.Context, *GetMedalByTokenIdReq) (*MedalDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMedalByTokenId not implemented")
}
func (UnimplementedMedalServer) mustEmbedUnimplementedMedalServer() {}
func (UnimplementedMedalServer) testEmbeddedByValue()               {}

// UnsafeMedalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MedalServer will
// result in compilation errors.
type UnsafeMedalServer interface {
	mustEmbedUnimplementedMedalServer()
}

func RegisterMedalServer(s grpc.ServiceRegistrar, srv MedalServer) {
	// If the following call panics, it indicates UnimplementedMedalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Medal_ServiceDesc, srv)
}

func _Medal_GetMedalsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedalsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServer).GetMedalsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medal_GetMedalsByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServer).GetMedalsByAddress(ctx, req.(*GetMedalsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Medal_GetMedalProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedalProofReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServer).GetMedalProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medal_GetMedalProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServer).GetMedalProof(ctx, req.(*GetMedalProofReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Medal_GetMedalByTokenId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedalByTokenIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServer).GetMedalByTokenId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medal_GetMedalByTokenId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServer).GetMedalByTokenId(ctx, req.(*GetMedalByTokenIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Medal_ServiceDesc is the grpc.ServiceDesc for Medal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Medal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medal.Medal",
	HandlerType: (*MedalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMedalsByAddress",
			Handler:    _Medal_GetMedalsByAddress_Handler,
		},
		{
			MethodName: "GetMedalProof",
			Handler:    _Medal_GetMedalProof_Handler,
		},
		{
			MethodName: "GetMedalByTokenId",
			Handler:    _Medal_GetMedalByTokenId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "medal.proto",
}
