// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: medal.proto

package medal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Medal_Ping_FullMethodName = "/medal.Medal/Ping"
)

// MedalClient is the client API for Medal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MedalClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type medalClient struct {
	cc grpc.ClientConnInterface
}

func NewMedalClient(cc grpc.ClientConnInterface) MedalClient {
	return &medalClient{cc}
}

func (c *medalClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Medal_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedalServer is the server API for Medal service.
// All implementations must embed UnimplementedMedalServer
// for forward compatibility.
type MedalServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMedalServer()
}

// UnimplementedMedalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMedalServer struct{}

func (UnimplementedMedalServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMedalServer) mustEmbedUnimplementedMedalServer() {}
func (UnimplementedMedalServer) testEmbeddedByValue()               {}

// UnsafeMedalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MedalServer will
// result in compilation errors.
type UnsafeMedalServer interface {
	mustEmbedUnimplementedMedalServer()
}

func RegisterMedalServer(s grpc.ServiceRegistrar, srv MedalServer) {
	// If the following call panics, it indicates UnimplementedMedalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Medal_ServiceDesc, srv)
}

func _Medal_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedalServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medal_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedalServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Medal_ServiceDesc is the grpc.ServiceDesc for Medal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Medal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medal.Medal",
	HandlerType: (*MedalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Medal_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "medal.proto",
}
