// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: medal.proto

package server

import (
	"context"

	"github.com/wwater/course-dao/app/medal/internal/logic"
	"github.com/wwater/course-dao/app/medal/internal/svc"
	"github.com/wwater/course-dao/app/medal/medal"
)

type MedalServer struct {
	svcCtx *svc.ServiceContext
	medal.UnimplementedMedalServer
}

func NewMedalServer(svcCtx *svc.ServiceContext) *MedalServer {
	return &MedalServer{
		svcCtx: svcCtx,
	}
}

func (s *MedalServer) Ping(ctx context.Context, in *medal.Request) (*medal.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
