// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: medal.proto

package server

import (
	"context"

	"github.com/wwater/course-dao/app/medal/internal/logic"
	"github.com/wwater/course-dao/app/medal/internal/svc"
	"github.com/wwater/course-dao/app/medal/medal/medal"
)

type MedalServer struct {
	svcCtx *svc.ServiceContext
	medal.UnimplementedMedalServer
}

func NewMedalServer(svcCtx *svc.ServiceContext) *MedalServer {
	return &MedalServer{
		svcCtx: svcCtx,
	}
}

// 根据地址获取勋章列表
func (s *MedalServer) GetMedalsByAddress(ctx context.Context, in *medal.GetMedalsReq) (*medal.GetMedalsResp, error) {
	l := logic.NewGetMedalsByAddressLogic(ctx, s.svcCtx)
	return l.GetMedalsByAddress(in)
}

// 根据地址获取勋章证明
func (s *MedalServer) GetMedalProof(ctx context.Context, in *medal.GetMedalProofReq) (*medal.GetMedalProofResp, error) {
	l := logic.NewGetMedalProofLogic(ctx, s.svcCtx)
	return l.GetMedalProof(in)
}

// 根据tokenId获取勋章详情
func (s *MedalServer) GetMedalByTokenId(ctx context.Context, in *medal.GetMedalByTokenIdReq) (*medal.MedalDetail, error) {
	l := logic.NewGetMedalByTokenIdLogic(ctx, s.svcCtx)
	return l.GetMedalByTokenId(in)
}

// 同步 IPFS 链接到数据库
func (s *MedalServer) UpdateMedalTokenUri(ctx context.Context, in *medal.UpdateMedalTokenUriReq) (*medal.UpdateMedalTokenUriResp, error) {
	l := logic.NewUpdateMedalTokenUriLogic(ctx, s.svcCtx)
	return l.UpdateMedalTokenUri(in)
}
