// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: medal.proto

package server

import (
	"context"

	"github.com/wwater/course-dao/app/medal/internal/logic"
	"github.com/wwater/course-dao/app/medal/internal/svc"
	"github.com/wwater/course-dao/app/medal/medal"
)

type MedalServer struct {
	svcCtx *svc.ServiceContext
	medal.UnimplementedMedalServer
}

func NewMedalServer(svcCtx *svc.ServiceContext) *MedalServer {
	return &MedalServer{
		svcCtx: svcCtx,
	}
}

// 根据地址获取勋章列表
func (s *MedalServer) GetMedalsByAddress(ctx context.Context, in *medal.GetMedalsReq) (*medal.GetMedalsResp, error) {
	l := logic.NewGetMedalsByAddressLogic(ctx, s.svcCtx)
	return l.GetMedalsByAddress(in)
}
