syntax = "proto3";

package medal;
option go_package="./medal";

message GetMedalsReq {
  string address = 1; // 用户钱包地址
}

message MedalInfo {
  uint64 token_id = 1;
  string tx_hash = 2;
  uint64 block_number = 3;
  uint32 level = 4;
}

message GetMedalsResp {
  repeated MedalInfo medals = 1;
}

message GetMedalProofReq {
  string address = 1;
}

message GetMedalProofResp {
  repeated string proof = 1;
  uint64 tokenId = 2;
}

message GetMedalByTokenIdReq {
  uint64 tokenId = 1;
}

message MedalDetail {
  uint64 tokenId = 1;
  string txHash = 2;
  uint64 blockNumber = 3;
  string mintTime = 4;
  uint32 level = 5;
}

message UpdateMedalTokenUriReq {
  uint32 level = 1;      // 勋章等级
  string tokenUri = 2;   // IPFS 链接
}

message UpdateMedalTokenUriResp {
  bool success = 1;
}

service Medal {
  // 根据地址获取勋章列表
  rpc GetMedalsByAddress(GetMedalsReq) returns (GetMedalsResp);
  // 根据地址获取勋章证明
  rpc GetMedalProof(GetMedalProofReq) returns (GetMedalProofResp);
  // 根据tokenId获取勋章详情
  rpc GetMedalByTokenId(GetMedalByTokenIdReq) returns (MedalDetail);
  // 同步 IPFS 链接到数据库
  rpc UpdateMedalTokenUri(UpdateMedalTokenUriReq) returns (UpdateMedalTokenUriResp);
}
