// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetMedalsReq struct {
	Address string `path:"address"`
}

type GetMedalsResp struct {
	Medals           []MedalInfo `json:"medals"`
	Proof            []string    `json:"proof"`
	ClaimableTokenId uint64      `json:"claimableTokenId"`
}

type MedalDetailReq struct {
	TokenId uint64 `path:"tokenId"`
}

type MedalDetailRes struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
	Type        string `json:"type"`
	CreateTime  string `json:"createTime"`
	TxHash      string `json:"txHash"`
}

type MedalInfo struct {
	TokenId     uint64 `json:"tokenId"`
	TxHash      string `json:"txHash"`
	BlockNumber uint64 `json:"blockNumber"`
}
