// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetMedalsReq struct {
	Address string `path:"address"`
}

type GetMedalsResp struct {
	Medals           []MedalInfo `json:"medals"`
	Proof            []string    `json:"proof"`
	ClaimableTokenId uint64      `json:"claimableTokenId"`
}

type LoginReq struct {
	Address   string `json:"address"`
	Message   string `json:"message"`
	Signature string `json:"signature"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type MedalDetailReq struct {
	TokenId uint64 `path:"tokenId"`
}

type MedalDetailRes struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
	Type        string `json:"type"`
	CreateTime  string `json:"createTime"`
	TxHash      string `json:"txHash"`
	Level       uint32 `json:"level"`
}

type MedalInfo struct {
	TokenId     uint64 `json:"tokenId"`
	TxHash      string `json:"txHash"`
	BlockNumber uint64 `json:"blockNumber"`
	Level       uint32 `json:"level"`
}

type NonceReq struct {
	Address string `json:"address"`
}

type NonceResp struct {
	Nonce string `json:"nonce"`
}

type SyncIPFSReq struct {
	Level int    `json:"level"` // 0:青铜, 1:白银, 2:黄金
	Name  string `json:"name"`  // 勋章名称
}

type SyncIPFSResp struct {
	TokenURI string `json:"tokenURI"`
}
