// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetMedalsReq struct {
	Address string `path:"address"`
}

type GetMedalsResp struct {
	Medals []MedalInfo `json:"medals"`
}

type MedalInfo struct {
	TokenId     uint64 `json:"tokenId"`
	TxHash      string `json:"txHash"`
	BlockNumber uint64 `json:"blockNumber"`
}
