// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: medal.proto

package medalclient

import (
	"context"

	"github.com/wwater/course-dao/app/medal/medal/medal"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMedalByTokenIdReq = medal.GetMedalByTokenIdReq
	GetMedalProofReq     = medal.GetMedalProofReq
	GetMedalProofResp    = medal.GetMedalProofResp
	GetMedalsReq         = medal.GetMedalsReq
	GetMedalsResp        = medal.GetMedalsResp
	MedalDetail          = medal.MedalDetail
	MedalInfo            = medal.MedalInfo

	Medal interface {
		// 根据地址获取勋章列表
		GetMedalsByAddress(ctx context.Context, in *GetMedalsReq, opts ...grpc.CallOption) (*GetMedalsResp, error)
		// 根据地址获取勋章证明
		GetMedalProof(ctx context.Context, in *GetMedalProofReq, opts ...grpc.CallOption) (*GetMedalProofResp, error)
		// 根据tokenId获取勋章详情
		GetMedalByTokenId(ctx context.Context, in *GetMedalByTokenIdReq, opts ...grpc.CallOption) (*MedalDetail, error)
	}

	defaultMedal struct {
		cli zrpc.Client
	}
)

func NewMedal(cli zrpc.Client) Medal {
	return &defaultMedal{
		cli: cli,
	}
}

// 根据地址获取勋章列表
func (m *defaultMedal) GetMedalsByAddress(ctx context.Context, in *GetMedalsReq, opts ...grpc.CallOption) (*GetMedalsResp, error) {
	client := medal.NewMedalClient(m.cli.Conn())
	return client.GetMedalsByAddress(ctx, in, opts...)
}

// 根据地址获取勋章证明
func (m *defaultMedal) GetMedalProof(ctx context.Context, in *GetMedalProofReq, opts ...grpc.CallOption) (*GetMedalProofResp, error) {
	client := medal.NewMedalClient(m.cli.Conn())
	return client.GetMedalProof(ctx, in, opts...)
}

// 根据tokenId获取勋章详情
func (m *defaultMedal) GetMedalByTokenId(ctx context.Context, in *GetMedalByTokenIdReq, opts ...grpc.CallOption) (*MedalDetail, error) {
	client := medal.NewMedalClient(m.cli.Conn())
	return client.GetMedalByTokenId(ctx, in, opts...)
}
