// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: medal.proto

package medalclient

import (
	"context"

	"github.com/wwater/course-dao/app/medal/medal"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = medal.Request
	Response = medal.Response

	Medal interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultMedal struct {
		cli zrpc.Client
	}
)

func NewMedal(cli zrpc.Client) Medal {
	return &defaultMedal{
		cli: cli,
	}
}

func (m *defaultMedal) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := medal.NewMedalClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
