// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: medal.proto

package medalclient

import (
	"context"

	"github.com/wwater/course-dao/app/medal/medal"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMedalsReq  = medal.GetMedalsReq
	GetMedalsResp = medal.GetMedalsResp
	MedalInfo     = medal.MedalInfo

	Medal interface {
		// 根据地址获取勋章列表
		GetMedalsByAddress(ctx context.Context, in *GetMedalsReq, opts ...grpc.CallOption) (*GetMedalsResp, error)
	}

	defaultMedal struct {
		cli zrpc.Client
	}
)

func NewMedal(cli zrpc.Client) Medal {
	return &defaultMedal{
		cli: cli,
	}
}

// 根据地址获取勋章列表
func (m *defaultMedal) GetMedalsByAddress(ctx context.Context, in *GetMedalsReq, opts ...grpc.CallOption) (*GetMedalsResp, error) {
	client := medal.NewMedalClient(m.cli.Conn())
	return client.GetMedalsByAddress(ctx, in, opts...)
}
