// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	course "github.com/wwater/course-dao/app/course/internal/handler/course"
	governance "github.com/wwater/course-dao/app/course/internal/handler/governance"
	"github.com/wwater/course-dao/app/course/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckMedalMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/premium",
					Handler: course.GetPremiumCourseHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/course"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/proposals",
				Handler: governance.ListProposalsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/governance"),
	)
}
