// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: medal.proto

package medal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMedalsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 用户钱包地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedalsReq) Reset() {
	*x = GetMedalsReq{}
	mi := &file_medal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedalsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsReq) ProtoMessage() {}

func (x *GetMedalsReq) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsReq.ProtoReflect.Descriptor instead.
func (*GetMedalsReq) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{0}
}

func (x *GetMedalsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MedalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       uint64                 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Level         uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedalInfo) Reset() {
	*x = MedalInfo{}
	mi := &file_medal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedalInfo) ProtoMessage() {}

func (x *MedalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedalInfo.ProtoReflect.Descriptor instead.
func (*MedalInfo) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{1}
}

func (x *MedalInfo) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *MedalInfo) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *MedalInfo) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *MedalInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetMedalsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medals        []*MedalInfo           `protobuf:"bytes,1,rep,name=medals,proto3" json:"medals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedalsResp) Reset() {
	*x = GetMedalsResp{}
	mi := &file_medal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedalsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalsResp) ProtoMessage() {}

func (x *GetMedalsResp) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalsResp.ProtoReflect.Descriptor instead.
func (*GetMedalsResp) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{2}
}

func (x *GetMedalsResp) GetMedals() []*MedalInfo {
	if x != nil {
		return x.Medals
	}
	return nil
}

type GetMedalProofReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedalProofReq) Reset() {
	*x = GetMedalProofReq{}
	mi := &file_medal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedalProofReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalProofReq) ProtoMessage() {}

func (x *GetMedalProofReq) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalProofReq.ProtoReflect.Descriptor instead.
func (*GetMedalProofReq) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{3}
}

func (x *GetMedalProofReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetMedalProofResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         []string               `protobuf:"bytes,1,rep,name=proof,proto3" json:"proof,omitempty"`
	TokenId       uint64                 `protobuf:"varint,2,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedalProofResp) Reset() {
	*x = GetMedalProofResp{}
	mi := &file_medal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedalProofResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalProofResp) ProtoMessage() {}

func (x *GetMedalProofResp) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalProofResp.ProtoReflect.Descriptor instead.
func (*GetMedalProofResp) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{4}
}

func (x *GetMedalProofResp) GetProof() []string {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *GetMedalProofResp) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type GetMedalByTokenIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       uint64                 `protobuf:"varint,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedalByTokenIdReq) Reset() {
	*x = GetMedalByTokenIdReq{}
	mi := &file_medal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedalByTokenIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalByTokenIdReq) ProtoMessage() {}

func (x *GetMedalByTokenIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalByTokenIdReq.ProtoReflect.Descriptor instead.
func (*GetMedalByTokenIdReq) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{5}
}

func (x *GetMedalByTokenIdReq) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type MedalDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       uint64                 `protobuf:"varint,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	MintTime      string                 `protobuf:"bytes,4,opt,name=mintTime,proto3" json:"mintTime,omitempty"`
	Level         uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedalDetail) Reset() {
	*x = MedalDetail{}
	mi := &file_medal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedalDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedalDetail) ProtoMessage() {}

func (x *MedalDetail) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedalDetail.ProtoReflect.Descriptor instead.
func (*MedalDetail) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{6}
}

func (x *MedalDetail) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *MedalDetail) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *MedalDetail) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *MedalDetail) GetMintTime() string {
	if x != nil {
		return x.MintTime
	}
	return ""
}

func (x *MedalDetail) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type UpdateMedalTokenUriReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`      // 勋章等级
	TokenUri      string                 `protobuf:"bytes,2,opt,name=tokenUri,proto3" json:"tokenUri,omitempty"` // IPFS 链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMedalTokenUriReq) Reset() {
	*x = UpdateMedalTokenUriReq{}
	mi := &file_medal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMedalTokenUriReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedalTokenUriReq) ProtoMessage() {}

func (x *UpdateMedalTokenUriReq) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedalTokenUriReq.ProtoReflect.Descriptor instead.
func (*UpdateMedalTokenUriReq) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMedalTokenUriReq) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdateMedalTokenUriReq) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

type UpdateMedalTokenUriResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMedalTokenUriResp) Reset() {
	*x = UpdateMedalTokenUriResp{}
	mi := &file_medal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMedalTokenUriResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedalTokenUriResp) ProtoMessage() {}

func (x *UpdateMedalTokenUriResp) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedalTokenUriResp.ProtoReflect.Descriptor instead.
func (*UpdateMedalTokenUriResp) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMedalTokenUriResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_medal_proto protoreflect.FileDescriptor

const file_medal_proto_rawDesc = "" +
	"\n" +
	"\vmedal.proto\x12\x05medal\"(\n" +
	"\fGetMedalsReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"x\n" +
	"\tMedalInfo\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\x04R\atokenId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\"9\n" +
	"\rGetMedalsResp\x12(\n" +
	"\x06medals\x18\x01 \x03(\v2\x10.medal.MedalInfoR\x06medals\",\n" +
	"\x10GetMedalProofReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"C\n" +
	"\x11GetMedalProofResp\x12\x14\n" +
	"\x05proof\x18\x01 \x03(\tR\x05proof\x12\x18\n" +
	"\atokenId\x18\x02 \x01(\x04R\atokenId\"0\n" +
	"\x14GetMedalByTokenIdReq\x12\x18\n" +
	"\atokenId\x18\x01 \x01(\x04R\atokenId\"\x93\x01\n" +
	"\vMedalDetail\x12\x18\n" +
	"\atokenId\x18\x01 \x01(\x04R\atokenId\x12\x16\n" +
	"\x06txHash\x18\x02 \x01(\tR\x06txHash\x12 \n" +
	"\vblockNumber\x18\x03 \x01(\x04R\vblockNumber\x12\x1a\n" +
	"\bmintTime\x18\x04 \x01(\tR\bmintTime\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\"J\n" +
	"\x16UpdateMedalTokenUriReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x1a\n" +
	"\btokenUri\x18\x02 \x01(\tR\btokenUri\"3\n" +
	"\x17UpdateMedalTokenUriResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa8\x02\n" +
	"\x05Medal\x12?\n" +
	"\x12GetMedalsByAddress\x12\x13.medal.GetMedalsReq\x1a\x14.medal.GetMedalsResp\x12B\n" +
	"\rGetMedalProof\x12\x17.medal.GetMedalProofReq\x1a\x18.medal.GetMedalProofResp\x12D\n" +
	"\x11GetMedalByTokenId\x12\x1b.medal.GetMedalByTokenIdReq\x1a\x12.medal.MedalDetail\x12T\n" +
	"\x13UpdateMedalTokenUri\x12\x1d.medal.UpdateMedalTokenUriReq\x1a\x1e.medal.UpdateMedalTokenUriRespB\tZ\a./medalb\x06proto3"

var (
	file_medal_proto_rawDescOnce sync.Once
	file_medal_proto_rawDescData []byte
)

func file_medal_proto_rawDescGZIP() []byte {
	file_medal_proto_rawDescOnce.Do(func() {
		file_medal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medal_proto_rawDesc), len(file_medal_proto_rawDesc)))
	})
	return file_medal_proto_rawDescData
}

var file_medal_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_medal_proto_goTypes = []any{
	(*GetMedalsReq)(nil),            // 0: medal.GetMedalsReq
	(*MedalInfo)(nil),               // 1: medal.MedalInfo
	(*GetMedalsResp)(nil),           // 2: medal.GetMedalsResp
	(*GetMedalProofReq)(nil),        // 3: medal.GetMedalProofReq
	(*GetMedalProofResp)(nil),       // 4: medal.GetMedalProofResp
	(*GetMedalByTokenIdReq)(nil),    // 5: medal.GetMedalByTokenIdReq
	(*MedalDetail)(nil),             // 6: medal.MedalDetail
	(*UpdateMedalTokenUriReq)(nil),  // 7: medal.UpdateMedalTokenUriReq
	(*UpdateMedalTokenUriResp)(nil), // 8: medal.UpdateMedalTokenUriResp
}
var file_medal_proto_depIdxs = []int32{
	1, // 0: medal.GetMedalsResp.medals:type_name -> medal.MedalInfo
	0, // 1: medal.Medal.GetMedalsByAddress:input_type -> medal.GetMedalsReq
	3, // 2: medal.Medal.GetMedalProof:input_type -> medal.GetMedalProofReq
	5, // 3: medal.Medal.GetMedalByTokenId:input_type -> medal.GetMedalByTokenIdReq
	7, // 4: medal.Medal.UpdateMedalTokenUri:input_type -> medal.UpdateMedalTokenUriReq
	2, // 5: medal.Medal.GetMedalsByAddress:output_type -> medal.GetMedalsResp
	4, // 6: medal.Medal.GetMedalProof:output_type -> medal.GetMedalProofResp
	6, // 7: medal.Medal.GetMedalByTokenId:output_type -> medal.MedalDetail
	8, // 8: medal.Medal.UpdateMedalTokenUri:output_type -> medal.UpdateMedalTokenUriResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_medal_proto_init() }
func file_medal_proto_init() {
	if File_medal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medal_proto_rawDesc), len(file_medal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medal_proto_goTypes,
		DependencyIndexes: file_medal_proto_depIdxs,
		MessageInfos:      file_medal_proto_msgTypes,
	}.Build()
	File_medal_proto = out.File
	file_medal_proto_goTypes = nil
	file_medal_proto_depIdxs = nil
}
